# Generated by Django 2.2.5 on 2020-12-03 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emlak', '0003_rentalad_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalad',
            name='balcony',
            field=models.CharField(choices=[('True', 'Evet'), ('False', 'Hayır')], default='None', max_length=10),
        ),
        migrations.AlterField(
            model_name='rentalad',
            name='category',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='emlak.Category'),
        ),
        migrations.AlterField(
            model_name='rentalad',
            name='furnished',
            field=models.CharField(choices=[('True', 'Evet'), ('False', 'Hayır')], default='None', max_length=10),
        ),
        migrations.AlterField(
            model_name='rentalad',
            name='location',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='emlak.Location'),
        ),
        migrations.AlterField(
            model_name='rentalad',
            name='status',
            field=models.CharField(choices=[('True', 'Evet'), ('False', 'Hayır')], default='False', max_length=10),
        ),
    ]
